### ISSUE TITLE
QR Code Generate Error

### ISSUE THREAD

**Issue by ZunairQA** [witwall/barcode-vba-macro-only#5]
Hi, so I'm trying to generate QR codes and I'm running into an error with some 27-character codes. Below is my line of code. The issue is it doesn't add the shape to excel for some reason. It works for example if "1783BMS20CGL" is all numbers or more/less characters. Would you be able to help? 

Call RenderQRCode(" Sheet1", "A1", "]2d{P}" & "1783BMS20CGL" & "{Q}" & 1 & "{D}03")

**Comment by JonasHeidelberg** [comment]
Have you tried the fork https://github.com/JonasHeidelberg/barcode-vba-macro-only ? Fixed a number of bugs there compared to here.26 jan. 2024 kl. 22:02 skrev ZunairQA ***@***.***>:﻿
Hi, so I'm trying to generate QR codes and I'm running into an error with some 27-character codes. Below is my line of code. The issue is it doesn't add the shape to excel for some reason. It works for example if "1783BMS20CGL" is all numbers or more/less characters. Would you be able to help?
Call RenderQRCode(" Sheet1", "A1", "]2d{P}" & "1783BMS20CGL" & "{Q}" & 1 & "{D}03")
